[package]
name = "bwl-meta"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[lib]
path = "src/lib.rs"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"
serde_json = "1.0"
image = "0.24"
leptess = "0.14"
clap = { version = "4.0", features = ["derive"] }
